# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 12:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('username', models.CharField(error_messages={'unique': '\u76f8\u540c\u7528\u6237\u540d\u5df2\u5b58\u5728'}, max_length=32, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='\u7528\u6237\u540d')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u542f\u7528')),
                ('is_staff', models.BooleanField(default=True, verbose_name='\u5141\u8bb8\u767b\u5f55')),
                ('is_admin', models.BooleanField(default=False, verbose_name='\u7ba1\u7406\u5458')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('real_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='\u90ae\u7bb1')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='\u7528\u6237\u7ec4')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8868',
                'verbose_name_plural': '\u7528\u6237\u8868',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AddressUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=150, verbose_name='\u5730\u5740')),
                ('zip_code', models.CharField(max_length=10, verbose_name='\u90ae\u7f16')),
                ('default_index', models.IntegerField(default=0, verbose_name='\u9ed8\u8ba4\u5730\u5740')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u5730\u5740\u7ba1\u7406',
                'verbose_name_plural': '\u5730\u5740\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ef7\u683c')),
                ('proxy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='\u4ee3\u7406\u4ef7\u683c')),
                ('description', models.CharField(max_length=200, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u8be6\u60c5',
                'verbose_name_plural': '\u5546\u54c1\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u5206\u7c7b')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.Type', verbose_name='\u7236\u7c7b')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u5206\u7c7b',
                'verbose_name_plural': '\u5546\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='UserOpenid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('appid', models.CharField(max_length=50)),
                ('head_img', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237OPENID')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u5fae\u4fe1\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u7528\u6237\u5fae\u4fe1\u4fe1\u606f\u8868',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Type', verbose_name='\u7c7b\u522b'),
        ),
    ]
