# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='images/', verbose_name='\u56fe\u7247\u5730\u5740')),
                ('commdity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Commodity', verbose_name='\u5546\u54c1\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u56fe\u7247',
                'verbose_name_plural': '\u5546\u54c1\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='CommodtyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u8bc4\u4ef7')),
                ('approval', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Commodity', verbose_name='\u5546\u54c1\u8bc4\u4ef7')),
            ],
        ),
    ]
