# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20181206_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityimage',
            name='commdity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Commodity', verbose_name='\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='commodtycomment',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Commodity', verbose_name='\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='\u5141\u8bb8\u767b\u5f55'),
        ),
    ]
