# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20181203_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u4ee3\u7406\u4ef7\u683c')),
            ],
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='proxy_price',
        ),
        migrations.AddField(
            model_name='commodity',
            name='count',
            field=models.IntegerField(default=1, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='type',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.Type', verbose_name='\u7236\u7c7b'),
        ),
        migrations.AddField(
            model_name='commodityproxy',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Commodity', verbose_name='\u4ee3\u7406\u5546\u54c1'),
        ),
        migrations.AddField(
            model_name='commodityproxy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4ee3\u7406\u4eba'),
        ),
    ]
