# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20181204_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u989c\u8272\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='CommoditySpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Commodity', verbose_name='\u5546\u54c1')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16, verbose_name='\u8ba2\u5355\u53f7')),
                ('count', models.IntegerField(default=1, verbose_name='\u5546\u54c1\u6570\u91cf')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='\u603b\u4ef7')),
                ('status', models.SmallIntegerField(choices=[(0, '\u672a\u652f\u4ed8'), (1, '\u5df2\u652f\u4ed8')], default=0, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('user_remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u987e\u5ba2\u63cf\u8ff0')),
                ('create_start', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0b\u5355\u65f6\u95f4')),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.AddressUser', verbose_name='\u8ba2\u5355\u5bc4\u5f80\u5730\u5740')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Commodity', verbose_name='\u5546\u54c1')),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='\u5c3a\u7801\u540d\u79f0')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Color', verbose_name='\u989c\u8272')),
            ],
        ),
        migrations.AddField(
            model_name='useropenid',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='useropenid',
            name='head_img',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5934\u50cf'),
        ),
        migrations.AddField(
            model_name='order',
            name='proxy_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxy_user', to=settings.AUTH_USER_MODEL, verbose_name='\u4ee3\u7406\u4eba'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='commodityspec',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Spec', verbose_name='\u89c4\u683c'),
        ),
    ]
