# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_auto_20181204_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '\u8ba2\u5355\u8868', 'verbose_name_plural': '\u8ba2\u5355\u8868'},
        ),
    ]
