# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_auto_20181205_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityspec',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='commodityspec',
            name='spec',
        ),
        migrations.AlterModelOptions(
            name='commodityproxy',
            options={'verbose_name': '\u5546\u54c1\u4ee3\u7406\u4eba', 'verbose_name_plural': '\u5546\u54c1\u4ee3\u7406\u4eba'},
        ),
        migrations.AlterModelOptions(
            name='commodtycomment',
            options={'verbose_name': '\u5546\u54c1\u8bc4\u4ef7', 'verbose_name_plural': '\u5546\u54c1\u8bc4\u4ef7'},
        ),
        migrations.RemoveField(
            model_name='addressuser',
            name='default_index',
        ),
        migrations.AddField(
            model_name='commodity',
            name='spec',
            field=models.ManyToManyField(blank=True, null=True, to='mall.Spec', verbose_name='\u5546\u54c1\u89c4\u683c'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_proxy',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u4ee3\u7406\u4eba'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group', verbose_name='\u7528\u6237\u7ec4'),
        ),
        migrations.DeleteModel(
            name='CommoditySpec',
        ),
    ]
