# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_auto_20181205_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Color', verbose_name='\u989c\u8272')),
            ],
            options={
                'verbose_name': '\u5e93\u5b58',
                'verbose_name_plural': '\u5e93\u5b58',
            },
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='color',
        ),
        migrations.AddField(
            model_name='stock',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Commodity', verbose_name='\u5546\u54c1'),
        ),
        migrations.AddField(
            model_name='stock',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Spec', verbose_name='\u5546\u54c1\u89c4\u683c'),
        ),
    ]
